# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('city_id', models.IntegerField()),
                ('mrp', models.CharField(max_length=100)),
                ('cut_price', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('available', models.IntegerField()),
                ('inventory', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Availability',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('reigon', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'City',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ManufactureName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'manufacture_name',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('pack_size', models.CharField(max_length=255)),
                ('drug_form', models.CharField(max_length=100)),
                ('pack_form', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'products',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductSaltMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salt_strength', models.CharField(max_length=255)),
                ('strength_unit', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'product_salt_map',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SaltName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'salt_name',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SkuType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'sku_type',
                'managed': False,
            },
        ),
    ]
